---
title: "ICES Sample Map"
author: "By SR Brunner"
date: "`r paste0('Date: ', format(Sys.time(), '%d.%m.%Y'))`"
output: html_document
runtime: shiny
---

<style type="text/css">
.main-container {
  max-width: 1800px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r load packages, include = FALSE}
library(shiny)
library(ggplot2)
library(knitr)
library(leaflet)
library(htmlwidgets)
library(tidyverse)
```

```{r load data, include=FALSE}
ices_temp <- read_csv("data/ices_temp.csv")
ices_psal <- read_csv("data/ices_psal.csv")
ices_cphl <- read_csv("data/ices_cphl.csv")
ices_doxy <- read_csv("data/ices_doxy.csv")
ices_download <- read_csv("data/ices_tot.csv")

# color palettes
temp_pal <- colorNumeric("RdYlBu", domain = ices_temp$mean_temp, reverse = TRUE)
psal_pal <- colorNumeric("Reds", domain = ices_psal$mean_psal, reverse = FALSE)
cphl_pal <- colorNumeric("Greens", domain = ices_cphl$mean_cphl, reverse = FALSE)
doxy_pal <- colorNumeric("Blues", domain = ices_doxy$mean_doxy, reverse = FALSE)

# about
about_text <- "This Map App displays temperatur, salinity, chlorophyll a and oxygen levels from measurements of oceanographic stations in the Baltic Sea averaged for the year 2019. The dataset was downloaded from the ices.dk website on 16/12/2020. Users can filter a range of stations via slider input and are also able to download this filtered data in CSV format."
```


```{r baltic sea app, include = TRUE, echo=FALSE, out.height='100%'}
ui <- bootstrapPage(
  theme = shinythemes::shinytheme('simplex'),
  mainPanel(
   leaflet::leafletOutput('baltic_map') 
  ),
  sidebarPanel(id = "controls",
               sliderInput('temp_ctrl', "Only display stations between ___ & ___ °C", 0, 25, value = c(0,25)),
               sliderInput('psal_ctrl', "Only display stations between ___ & ___ psu", 0, 30, value = c(0,30)),
               downloadButton("download_data", "Download filtered data"),
               actionButton("about", "About"),
               checkboxInput("legend", "Show legend", TRUE)
                )
)
server <- function (input,
                    output,
                    session) {
  
  # about section
  observeEvent(input$about, {
    showModal(modalDialog(about_text))
  })
  
  # reactives
  temp_react <- reactive({
    ices_temp %>%
      filter(mean_temp > input$temp_ctrl[1] & mean_temp < input$temp_ctrl[2])
      
  })
  psal_react <- reactive({
    ices_psal %>%
      filter(mean_psal > input$psal_ctrl[1] & mean_psal < input$psal_ctrl[2])
      
  })
  
  download_react <- reactive({
    ices_download %>%
      filter(mean_temp > input$temp_ctrl[1] & mean_temp < input$temp_ctrl[2]) %>%
      filter(mean_psal > input$psal_ctrl[1] & mean_psal < input$psal_ctrl[2])
  })
  
  output$baltic_map <- leaflet::renderLeaflet({
    
    # output
    leaflet(height = '100%',
            options = leafletOptions(minZoom = 4,
                                 dragging = TRUE)) %>%
    setView(lng = 19.8633, lat = 58.48803, zoom = 5) %>%
    setMaxBounds(lng1 = max(ices_temp$lon) + 2,
                 lat1 = max(ices_temp$lat) + 2,
                 lng2 = min(ices_temp$lon) - 2,
                 lat2 = min(ices_temp$lat) - 2) %>%
    addTiles(group = "OSM") %>%
    addProviderTiles(provider = "CartoDB", group = "CartoDB") %>%
    addProviderTiles(provider = "Esri", group = "Esri") %>%
    addCircleMarkers(data = ices_temp, 
                     layerId = "tempura",
                     lng = ices_temp$lon, 
                     lat = ices_temp$lat,
                     group = "Temperature",
                     radius = 3,
                     color = ~temp_pal(mean_temp),
                     popup = ~paste0("Station number: ", 
                                     Station, "<br/>Mean temperature: ", 
                                     round(mean_temp, 2), "°C")) %>%
    addCircleMarkers(data = ices_psal, 
                     lng = ices_psal$lon, 
                     lat = ices_psal$lat,
                     group = "Salinity",
                     radius = 3,
                     color = ~psal_pal(mean_psal),
                     popup = ~paste0("Station number: ", 
                                     Station, "<br/>Mean salinity: ", 
                                     round(mean_psal, 2), "psu")) %>%
    hideGroup(group = c("Salinity", "Chlorophyll a Levels", "Oxygen Levels")) %>%
    addLegend(data = ices_temp, 
              values = rev(seq(min(ices_temp$mean_temp), max(ices_temp$mean_temp), 5)),
              group = "Temperature",
              position = "bottomright",
              pal = temp_pal) %>%
    addLayersControl(baseGroups = c("OSM", "CartoDB", "Esri"),
                     overlayGroups = c("Temperature", "Salinity", "Chlorophyll a Levels", "Oxygen Levels"),
                     options = layersControlOptions(collapsed = FALSE)) %>%
    htmlwidgets::onRender(("
              function() {
                $('.leaflet-control-layers-list').prepend('<label style=\"text-align:center\">Choose Base Layer</label>');
                $('.leaflet-control-layers-overlay').prepend('<label style=\"text-align:center\">Choose Data Layer</label>');
              }"))
  })
  
  observe({
    
    temp_data <- temp_react()
    leafletProxy("baltic_map", data = temp_data) %>%
      removeShape(layerId = "tempura") %>%
      addCircleMarkars(layerId = "new",
                     lng = temp_data$lon,
                     lat = temp_data$lat,
                     group = "Temperature",
                     radius = 3,
                     color = ~temp_pal(temp_data$mean_temp),
                     popup = ~paste0("Station number: ",
                                     Station, "<br/>Mean temperature: ",
                                     round(mean_temp, 2), "°C"))
  })

  # download
  output$download_data <- downloadHandler(
    filename = function() {
      paste0("ices_baltic_2019", ".csv")
    },
    content = function(file) {
      write.csv(download_react(), file, row.names = FALSE)
    }
  )
  
}
shinyApp(ui = ui, server = server)
```

&nbsp;
<hr />
<p style="text-align: center;">A work by <a href="https://www.kaggle.com/reminho">SR Brunner</a></p>
<p style="text-align: center;"><span style="color: #808080;"><em>remy.data@gmx.ch</em></span></p>

<!-- Add icon library -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<!-- Add font awesome icons -->
<p style="text-align: center;">
    <a href="https://www.linkedin.com/in/wanaka/" class="fa fa-linkedin"></a>
</p>

&nbsp;


